apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-server
spec:
  selector:
    matchLabels:
      app: flask-server
  template:
    metadata:
      labels:
        app: flask-server
    spec:
      containers:
      - name: flask-server
        image: flask-server
        ports:
        - containerPort: 80
