apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: flask-server
  newName: lucasfss/gitops
  newTag: latest
- name: goserver
  newName: lucasfss/gitops-curse
  newTag: cc6dccb90472ba2fd6a2d496a570d932b521d8fa
