apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: flask-server
  newName: lucasfss/gitops-curse
  newTag: 429b36c3269b775ef1f98b49371b58f9e5f650f1
