apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: flask-server
  newName: lucasfss/gitops
  newTag: latest
- name: flask-server==lucasfss/gitops-curse
  newTag: latest
